#ifndef __CMG_CONTROLLER_SERVICE_IDL__
#define __CMG_CONTROLLER_SERVICE_IDL__

module OpenHRP
{
  interface CMGcontrollerService
  {
    void echo(in string msg);
    void startCMGcontroller();
    void stopCMGcontroller();
  };
};

#endif
