#ifndef __CMG_CONTROLLER_SERVICE_IDL__
#define __CMG_CONTROLLER_SERVICE_IDL__

module OpenHRP
{
  interface CMGcontrollerService
  {
    struct cmgParam {
      boolean is_sim;
      double spin_rpm;
      double deadband_th;
      double back_dq;
      double kp;
    };

    void echo(in string msg);
    void startCMGcontroller();
    void stopCMGcontroller();
    void getParameter(out cmgParam i_param);
    void setParameter(in cmgParam i_param);
  };
};

#endif
